### ISSUE TITLE
Issue installing ug4

### ISSUE THREAD

**Issue by jarosado0911** [UG4/ughub#18]
I am following the directions for installing ug4 on my Windows machine, I installed jom and ran cmake -G "NMake Makefiles JOM" -DCMAKE_BUILD_TYPE=Release -DSTATIC_BUILD=ON .. in PowerShell 7 and it sends me an error (see file1.txt)
[file1.txt](https://github.com/UG4/ughub/files/4907558/file1.txt) I then switch to visual studio command prompt VS2017 and it states (see file2.jpg)
![file2](https://user-images.githubusercontent.com/57325500/87233236-b1ded100-c393-11ea-82ff-6b0bdaf3a6cc.JPG) I am running Windows 10 Pro, Version	10.0.18362 Build 18362, Processor	Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz, 3601 Mhz, 4 Core(s), 8 Logical Processor(s)
System Model	XPS 8700
System Type	x64-based PC
I did modify the paths in SystemAdvancedProperties.exe as well. I am not sure what could be wrong or if I set something wrong, any suggestions are much appreciated. Thanks :)

**Comment by stephanmg** [comment]
Do you have `jom` installed and in your `PATH`? Also you do not need to use `jom`  necessarily (Without it should compile slower / not parallel. IIRC it is basically a clone of nmake, to use all processing power / cores (threads) of your host)

**Comment by jarosado0911** [comment]
Yes, I have jom and I added it in my PATH. I will try without jom to see if it works.

**Comment by stephanmg** [comment]
You could also have a look at [this](https://github.com/UG4/ugcore/blob/master/appveyor.yml).

**Comment by jarosado0911** [comment]
okay, How do I use this? Would I call this script in the shell? Thanks :)

**Comment by stephanmg** [comment]
> okay, How do I use this? Would I call this script in the shell? Thanks :)

This is an example how to build on Appveyor (Windows). There are specific lines of code which might be interested, the pipeline script you should not run locally. But, maybe test before if you can get it to work without `jom`.

**Comment by sreiter** [comment]
There are several different options to compile on windows. Jom is probably a bit outdated. Here are two alternatives. In both cases please completey clear your build folder befor trying any of them (e.g. remove and then recreate it). Changing compilers in an existing cmake-build folder is not easily possible, to my knowledge.
    
Visual Studio project files:
1.  cmake -DDIM=3 -DCPU=1 -DSTATIC_BUILD=ON ../..
2.  open the generated UG4.sln in Visual Studio
3.  Choose 'Release' from the dropdown menu (both debug and release builds are possible from within Visual Studio)
4.  Click Build->BuildSolution (F7) from the menu bar.
5.  ugshell.exe will be generated to bin/Release
6.  (Note that the cmake call above works out of the box, at least on my system. No need to call vcvars64.bat

Ninja makefiles
1.  As with jom, after starting cmd.exe, first run vcvars64.bat (e.g.: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat")
2.  Make sure that ninja.exe is located in your bin folder and that this folder has been added to your PATH variable (same as with jom).
3.  Call:
     > cmake -G"Ninja" -DDIM=3 -DCPU=1 -DSTATIC_BUILD=ON -DCMAKE_BUILD_TYPE=Release ../..
     > ninja

Compilation with ninja makefiles is nice if you want to integrate your build into SublimeText or maybe also Eclipse. Note that ninja also requires an installation of Visual Studio. It is closer to the Unix workflow, that's why there may be less issues with runnign ugshell once it has been compiled.

On the other hand, Visual Studio project files can be generated with less hassle (no need to download ninja, no need to run vcvars64.bat) and can be easily compiled, too. Compiled executables are added to bin/Release instead of bin directly. This may cause some issues down the road when executing commands. Please report back if this leads to issue.

Since most developers of UG4 work with Unix systems, the Windows subsystem for Linux may be an interesting option, too (https://docs.microsoft.com/en-us/windows/wsl/install-win10). This is how I worked with UG4 for quite some time. You can then closely follow the installation steps for Unix. You should make sure to Place the UG4 folder at a place on your disc which you can easily reach from your explorer.

Hope this helps somewhat. Let us know what worked for you.
Kind regards,
Sebastian

**Comment by stephanmg** [comment]
Hello @sreiter,

thanks for your answer.
I recently stumbled across WSL for another project. Will WSL1 be enough or did you update to WSL2 to build ug4? 

There is also ccmake an curses user interface to review and configure the settings in your current CMake build folder, if this would be of interest at all, invoke via `ccmake .`.

best,
Stephan

**Comment by jarosado0911** [comment]
Hello @sreiter ,

Thank you this helps. I attempted using Visual Studio project files and that worked. However, when I run poisson.lua it throws the error   % EXCEPTION on Proc 0: UGError thrown
 %   Error traceback (innermost first):
 %   0: Couldn't find script ug_util.lua
 %      Search paths: Current Path = C:\Users\jaros_000\ug4\apps\Examples\, SCRIPT_PATH = C:\Users\jaros_000\ug4\bin\Release\..\ugcore\scripts, APPS_PATH = C:\Users\jaros_000\ug4\bin\Release\..\apps, ROOT_PATH = C:\Users\jaros_000\ug4\bin\Release\..
 %
 %      [at C:\Users\jaros_000\ug4\ugcore\ugbase\bindings\lua\lua_util.cpp:162]
 % In CALL to function 'bool ug_load_script(string)'
 %    ARGS: (cstring "ug_util.lua")
 % In FILE: @C:\Users\jaros_000\ug4\apps\Examples\poisson.lua:33
 % At LINE: 'ug_load_script("ug_util.lua")'
LUA-ERROR! Call stack:
   1  @C:\Users\jaros_000\ug4\apps\Examples\poisson.lua:33   ug_load_script("ug_util.lua")
 % ABORTING script parsing.

I am guessing it can't find the util folder in ugcore. Is this the issue that you were referring to? Thanks.


EDIT: I moved the ugshell.exe into the bin directly i.e. I moved it out of 'Release' and into bin and now I no longer get the error. I am not sure why this worked :)

**Comment by sreiter** [comment]
Hello @jarosado0911,

When ugshell.exe lies in the ug4/bin folder, the paths to the utility scripts will be found correctly. Here's a little trick how you don't have to copy the file manually after each rebuild:

Starting from your UG4 root folder, for this example `D:/code/ug4`, please perform the following steps:

1. Create a build folder (e.g. `mkdir build_vs`)
2. Navigate into that folder (`cd build_vs`)
3. Execute the following cmake command (type in one line):
    `cmake -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=D:/code/ug4/bin -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG=D:/code/ug4/bin -DSTATIC_BUILD=ON -DConvectionDiffusion=ON ..`
4. Execute `UG4.sln` to open the UG4 project in Visual Studio
5. Choose `Release` build at the top of the Visual Studio IDE and hit F7 (build project).
6. When the build is done, navigate to `D:/code/ug4/bin` in your terminal/shell/cmd.exe.
7. Execute `ugshell.exe -ex Examples/poisson.lua`

ugshell.exe should now be created directly in the ug4/bin folder. You'll have to specify the bin folder with a full path in the cmake call above. Relative paths won't work in that case, since cmake seems to interpret them relative to some internal current build directory.

We could think about always automatically specifying those cmake variables in our build system. All information would be available there.

Kind regards,
Sebastian

**Comment by sreiter** [comment]
Hello @stephanmg,

All you need is git, cmake, g++/clang, python3, maybe ninja, etc. Pretty basic stuff. I think both version should be fine. I used WSL back in 2018 and before, if I'm not mistaken. So I'm pretty sure it was WSL1.

Kind regards,
Sebastian

**Comment by stephanmg** [comment]
> Hello @stephanmg,
> 
> All you need is git, cmake, g++/clang, python3, maybe ninja, etc. Pretty basic stuff. I think both version should be fine. I used WSL back in 2018 and before, if I'm not mistaken. So I'm pretty sure it was WSL1.

Thanks, will give it a shot. (Also one could argue this is not a real native Windows build then, right?)

> 
> Kind regards,
> Sebastian

**Comment by stephanmg** [comment]
@jarosado0911 if this resolved your issue, please comment and close. Btw. you can always look into the `.appveyor.yml` of ugcore, in which ug4 is build natively - or in some of my projects in the NeuroBox3D organization.

**Comment by jarosado0911** [comment]
Thank you all, this was very helpful. It works nicely! :)
