### ISSUE TITLE
uninstallPackage cmd

### ISSUE THREAD

**Issue by stephanmg** [UG4/ughub#7]
If a package is installed, for instance by accident, it would be good to have a uninstallPackage function.

Also if a source should be removed, cf. #4, this would be helpful. 
Consider for instance that a source is to be removed. If the source is removed, one should be able to decide if the corresponding "installed" packages from this source should also be removed or not.

**Comment by sreiter** [comment]
I think you're right, that such a command would be useful. However, one would have to take care so that no local changes are accidentally deleted. To this end one would have to check the following:

1.  Does the package have a remote upstream repository

**Comment by sreiter** [comment]
I think you're right that such a command would be useful. However, one would have to take care so that no local changes are accidentally deleted. To this end one would have to check the following during 'uninstall':
- [x] Check if the local package has an associated remote upstream repository.
- [ ] Check whether the local repository contains uncommited changes.
- [ ] Check whether the local repository contains commits that were not yet pushed to the remote 
  repository.

If any of those checks fails, an error-message should be printed together with the hint that the '--force' option can be used to delete the package(s) despite those issues.

**Comment by stephanmg** [comment]
Should be all addressed right now, see changeset for cf. #12 and #13.
